language: python
python:
  - "2.7"
  - "3.3"
install:
  - sudo apt-get install libfreetype6 libfreetype6-dev zlib1g-dev
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so ~/virtualenv/python2.7/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so ~/virtualenv/python2.7/lib/
  - pip install Django==1.5 Pillow==2.0.0 six  --use-mirrors
script: cd testproject && python manage.py test captcha
